kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ang-l-fw
runtimeConfig:
  "api/alpha": "false"
networking:
  ipFamily: ipv6
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
nodes:
  - role: control-plane
  - role: worker
